# Generated by Django 3.2.4 on 2021-07-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.proposal'),
        ),
    ]
