# Generated by Django 3.2.4 on 2021-07-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_contract_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_contracts', to='accounts.project'),
        ),
    ]
