# Generated by Django 3.2.4 on 2021-07-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contract_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='project',
        ),
    ]
